### PR TITLE
Resolve: MPI has no more C++ binding

### LINKED ISSUE #1: MPI has no more C++ binding
Looks like C++ bindings are deprecated since MPI2.2 and not part of the standard from MPI3.X.
Should we consider to replace them by C bindings ?

### PR DESCRIPTION
**Pull request by MisterFruits**
Closes #1 :
Replaced all C++ bindings with C ones.
Not sure the creation of `MPI_get_rank` and `MPI_get_size` suits the standards. I wonder what's the best spot where to put them. I mainly created these 2 functions because of constructors of `SimulationNBodyMPI` and the fact that `MPI_Comm_get_rank/size` returns value with references.

### CODE REVIEW

**Comment by kouchy** [comment]
First thx for your work @MisterFruits.
I have no problem with your `MPI_get_rank` and `MPI_get_size` functions. It looks fine to me.
Did you tested it?

**Comment by MisterFruits** [comment]
Well, `make` with and without MPI ends well. I have to test execution now.
Do you have som advise ? Some set of parameters I should try. Compare MPI perfs maybe ? I wont be able to run soon on a cluster with MPI<3.x so I'm not sure how I could test MPI perfs (maybe regarding the scalar code and checking the scalability ?)

**Comment by kouchy** [comment]
Ok if it compiles it is a good start. 
To test if it works well you can run the MPI code on a multi-core CPU (your laptop for instance), you can create one MPI process per core and check if you have a good speedup (the speedup should be equal to the number or cores). 
You can compare MPI performance to OpenMP performance, it should be close.

**Comment by kouchy** [comment]
I ran OMP and MPI versions on my laptop (4 cores with 2-SMT = 8 HW threads, Turbo boost ON).

Single threaded (= sequential version)
`OMP_NUM_THREADS=1 ./bin/Release/murb -n 10000 -i 1000 -v --im 13 --nv`:
=> `Entire simulation took 32282.672 ms (57.692 Gflop/s)`

OMP 4 threads
`OMP_NUM_THREADS=4 ./bin/Release/murb -n 10000 -i 1000 -v --im 13 --nv`:
=> `Entire simulation took 9785.240 ms (190.333 Gflop/s)`
 
MPI 4 processes
`OMP_NUM_THREADS=1 mpirun -np 4 ./bin/Release/murb -n 10000 -i 1000 -v --im 103 --nv`:
=> `Entire simulation took 9693.439 ms (192.136 Gflop/s)`

OMP 8 threads
`OMP_NUM_THREADS=8 ./bin/Release/murb -n 10000 -i 1000 -v --im 13 --nv`:
=> `Entire simulation took 9345.376 ms (199.292 Gflop/s)`

MPI 4 processes + 2 OMP threads per process
`OMP_NUM_THREADS=2 mpirun -np 4 ./bin/Release/murb -n 10000 -i 1000 -v --im 103 --nv`:
=> `Entire simulation took 9350.701 ms (199.179 Gflop/s)`

The performance results look good to me :-).
I also quickly checked if the physic continue to work, by eyes it looks like ok but with the MPI version, if I remember well, only the bodies from the first process are displayed, other are not shown.

**Pull request merged**
